// Generated class bindings for Roblox API
import roblox/option.{type Option}
import roblox/signal.{type RBXScriptSignal}
import roblox/dynamic.{type Dynamic}
import roblox/types.{type Actor, type GenerationService, type Instance, type MeshPart, type OptionDouble, type OptionFunction, type OptionInt64, type Player, type SecurityCapabilities, type UniqueId}

/// Roblox: `GenerationService.ConnectAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#ConnectAsync
@luau.method("ConnectAsync")
pub fn connect_async(instance: GenerationService, session_id: String, sdp: String, type_: String, relay: String) -> Dynamic

/// Roblox: `GenerationService.DisconnectAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#DisconnectAsync
@luau.method("DisconnectAsync")
pub fn disconnect_async(instance: GenerationService, session_id: String) -> Bool

/// Starts the generation of a new 3D mesh from a text prompt and returns unique IDs used to track and retrieve the result.
///
/// Roblox: `GenerationService.GenerateMeshAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GenerateMeshAsync
///
/// Parameters:
/// - `instance`: Service that allows developers to generate 3D objects from text prompts.
/// - `inputs`: A dictionary containing the mesh generation prompts. Currently, the only supported key is the Prompt (string) that describes the mesh to generate.
/// - `player`: The Player requesting the generation.
/// - `options`: A dictionary for additional generation options to influence the result. The optional SuggestedSize key (Vector3) represents a size guide for the generated asset, meaning GenerationService will attempt to create a model with a size and proportion similar to the provided Vector3, although there is no guarantee on the final output size.
/// - `intermediateResultCallback`: A callback function triggered with intermediate generation results. Useful for retrieving early mesh versions before textures are applied.
///
/// Returns:
/// - A tuple of the generation ID (a unique ID returned for each invocation of GenerateMeshAsync()) and context ID (not currently used).
@luau.method("GenerateMeshAsync")
pub fn generate_mesh_async(instance: GenerationService, inputs: Dynamic, player: Player, options: Dynamic, intermediate_result_callback: OptionFunction) -> Dynamic

/// Enables generation of multi-mesh geometries according to provided inputs and a schema.
///
/// Roblox: `GenerationService.GenerateModelAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GenerateModelAsync
///
/// Parameters:
/// - `instance`: Service that allows developers to generate 3D objects from text prompts.
/// - `inputs`: A table representing conditioning inputs with the following keys: TextPrompt — String description of the object to generate. Size — Optional Vector3 describing the object size to generate. This is only approximate; scale the model extents post‑generation if you need a specific size. MaxTriangles — Optional integer describing the maximum number of triangles that the returned model will contain. Lower values result in more faceted and low-poly generations. GenerateTextures — true (default) textures the resulting generation, while false will not generate textures.
/// - `schema`: Table representing the generation schema. Must contain a PredefinedSchema key with a string value; current valid options are Car5 for a basic vehicle chassis consisting of five Models, or Body1 which results in a single mesh output.
/// - `options`: Currently not used; reserved for future customization options.
///
/// Returns:
/// - Tuple with the following elements: A standard Model container instance that is compliant with the specified schema. A table containing a UUID and other metadata about the generation.
@luau.method("GenerateModelAsync")
pub fn generate_model_async(instance: GenerationService, inputs: Dynamic, schema: Dynamic, options: Dynamic) -> Dynamic

/// Roblox: `GenerationService.GetVideoGenSessionAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetVideoGenSessionAsync
@luau.method("GetVideoGenSessionAsync")
pub fn get_video_gen_session_async(instance: GenerationService) -> Dynamic

/// Roblox: `GenerationService.GetVideoGenTriggersAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetVideoGenTriggersAsync
@luau.method("GetVideoGenTriggersAsync")
pub fn get_video_gen_triggers_async(instance: GenerationService, session_id: String, lookback_seconds: Int) -> Dynamic

/// Retrieves and loads a mesh generated by GenerationService:GenerateMeshAsync() using the provided generationId.
///
/// Roblox: `GenerationService.LoadGeneratedMeshAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#LoadGeneratedMeshAsync
///
/// Parameters:
/// - `instance`: Service that allows developers to generate 3D objects from text prompts.
/// - `generationId`: The unique ID returned by GenerateMeshAsync(). Identifies the mesh to load.
///
/// Returns:
/// - The generated asset, returned as a Model with a single MeshPart containing an EditableMesh.
@luau.method("LoadGeneratedMeshAsync")
pub fn load_generated_mesh_async(instance: GenerationService, generation_id: String) -> MeshPart

/// Roblox: `GenerationService.StartVideoGenSessionAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#StartVideoGenSessionAsync
@luau.method("StartVideoGenSessionAsync")
pub fn start_video_gen_session_async(instance: GenerationService, session_id: String, prompt: String, image_data: String, image_s3_reference: String, triggers: Dynamic) -> Bool

/// Roblox: `GenerationService.UpdateVideoGenSessionPromptAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#UpdateVideoGenSessionPromptAsync
@luau.method("UpdateVideoGenSessionPromptAsync")
pub fn update_video_gen_session_prompt_async(instance: GenerationService, session_id: String, prompt: String, image_data: String, image_s3_reference: String, mode: String) -> Bool

/// Roblox: `GenerationService.UpdateVideoGenSessionTriggersAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#UpdateVideoGenSessionTriggersAsync
@luau.method("UpdateVideoGenSessionTriggersAsync")
pub fn update_video_gen_session_triggers_async(instance: GenerationService, session_id: String, triggers: Dynamic) -> Bool

/// Gets Roblox property `GenerationService.Archivable`.
///
/// Roblox: `GenerationService.Archivable`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Archivable
@luau.property("Archivable")
pub fn get_archivable(instance: GenerationService) -> Bool

/// Sets Roblox property `GenerationService.Archivable`.
///
/// Roblox: `GenerationService.Archivable`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Archivable
@luau.set_property("Archivable")
pub fn set_archivable(instance: GenerationService, value: Bool) -> GenerationService

/// Gets Roblox property `GenerationService.Capabilities`.
///
/// Roblox: `GenerationService.Capabilities`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Capabilities
@luau.property("Capabilities")
pub fn get_capabilities(instance: GenerationService) -> SecurityCapabilities

/// Sets Roblox property `GenerationService.Capabilities`.
///
/// Roblox: `GenerationService.Capabilities`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Capabilities
@luau.set_property("Capabilities")
pub fn set_capabilities(instance: GenerationService, value: SecurityCapabilities) -> GenerationService

/// Gets Roblox property `GenerationService.Name`.
///
/// Roblox: `GenerationService.Name`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Name
@luau.property("Name")
pub fn get_name(instance: GenerationService) -> String

/// Sets Roblox property `GenerationService.Name`.
///
/// Roblox: `GenerationService.Name`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Name
@luau.set_property("Name")
pub fn set_name(instance: GenerationService, value: String) -> GenerationService

/// Gets Roblox property `GenerationService.Parent`.
///
/// Roblox: `GenerationService.Parent`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Parent
@luau.property("Parent")
pub fn get_parent(instance: GenerationService) -> Instance

/// Sets Roblox property `GenerationService.Parent`.
///
/// Roblox: `GenerationService.Parent`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Parent
@luau.set_property("Parent")
pub fn set_parent(instance: GenerationService, value: Instance) -> GenerationService

/// Gets Roblox property `GenerationService.RobloxLocked`.
///
/// Roblox: `GenerationService.RobloxLocked`
/// ThreadSafety: ReadSafe
/// Tags: Hidden
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#RobloxLocked
@luau.property("RobloxLocked")
pub fn get_roblox_locked(instance: GenerationService) -> Bool

/// Gets Roblox property `GenerationService.Sandboxed`.
///
/// Roblox: `GenerationService.Sandboxed`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Sandboxed
@luau.property("Sandboxed")
pub fn get_sandboxed(instance: GenerationService) -> Bool

/// Sets Roblox property `GenerationService.Sandboxed`.
///
/// Roblox: `GenerationService.Sandboxed`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Sandboxed
@luau.set_property("Sandboxed")
pub fn set_sandboxed(instance: GenerationService, value: Bool) -> GenerationService

/// Gets Roblox property `GenerationService.SourceAssetId`.
///
/// Roblox: `GenerationService.SourceAssetId`
/// ThreadSafety: ReadSafe
/// Tags: Hidden
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#SourceAssetId
@luau.property("SourceAssetId")
pub fn get_source_asset_id(instance: GenerationService) -> OptionInt64

/// Gets Roblox property `GenerationService.UniqueId`.
///
/// Roblox: `GenerationService.UniqueId`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#UniqueId
@luau.property("UniqueId")
pub fn get_unique_id(instance: GenerationService) -> UniqueId

/// Roblox: `GenerationService.AddTag`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#AddTag
@luau.method("AddTag")
pub fn add_tag(instance: GenerationService, tag: String) -> Nil

/// Roblox: `GenerationService.ClearAllChildren`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#ClearAllChildren
@luau.method("ClearAllChildren")
pub fn clear_all_children(instance: GenerationService) -> Nil

/// Roblox: `GenerationService.Clone`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Clone
@luau.method("Clone")
pub fn clone(instance: GenerationService) -> Instance

/// Roblox: `GenerationService.Destroy`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Destroy
@luau.method("Destroy")
pub fn destroy(instance: GenerationService) -> Nil

/// Roblox: `GenerationService.FindFirstAncestor`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstAncestor
@luau.method("FindFirstAncestor")
pub fn find_first_ancestor(instance: GenerationService, name: String) -> Option(Instance)

/// Roblox: `GenerationService.FindFirstAncestorOfClass`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstAncestorOfClass
@luau.method("FindFirstAncestorOfClass")
pub fn find_first_ancestor_of_class(instance: GenerationService, class_name: String) -> Option(Instance)

/// Roblox: `GenerationService.FindFirstAncestorWhichIsA`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstAncestorWhichIsA
@luau.method("FindFirstAncestorWhichIsA")
pub fn find_first_ancestor_which_is_a(instance: GenerationService, class_name: String) -> Option(Instance)

/// Roblox: `GenerationService.FindFirstChild`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstChild
@luau.method("FindFirstChild")
pub fn find_first_child(instance: GenerationService, name: String, recursive: Bool) -> Option(Instance)

/// Roblox: `GenerationService.FindFirstChildOfClass`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstChildOfClass
@luau.method("FindFirstChildOfClass")
pub fn find_first_child_of_class(instance: GenerationService, class_name: String) -> Option(Instance)

/// Roblox: `GenerationService.FindFirstChildWhichIsA`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstChildWhichIsA
@luau.method("FindFirstChildWhichIsA")
pub fn find_first_child_which_is_a(instance: GenerationService, class_name: String, recursive: Bool) -> Option(Instance)

/// Roblox: `GenerationService.FindFirstDescendant`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#FindFirstDescendant
@luau.method("FindFirstDescendant")
pub fn find_first_descendant(instance: GenerationService, name: String) -> Option(Instance)

/// Roblox: `GenerationService.GetActor`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetActor
@luau.method("GetActor")
pub fn get_actor(instance: GenerationService) -> Actor

/// Roblox: `GenerationService.GetAttribute`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetAttribute
@luau.method("GetAttribute")
pub fn get_attribute(instance: GenerationService, attribute: String) -> Dynamic

/// Roblox: `GenerationService.GetAttributeChangedSignal`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetAttributeChangedSignal
@luau.method("GetAttributeChangedSignal")
pub fn get_attribute_changed_signal(instance: GenerationService, attribute: String) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.GetAttributes`
/// ThreadSafety: Safe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetAttributes
@luau.method("GetAttributes")
pub fn get_attributes(instance: GenerationService) -> Dynamic

/// Roblox: `GenerationService.GetChildren`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetChildren
@luau.method("GetChildren")
pub fn get_children(instance: GenerationService) -> List(Instance)

/// Roblox: `GenerationService.GetDescendants`
/// ThreadSafety: Safe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetDescendants
@luau.method("GetDescendants")
pub fn get_descendants(instance: GenerationService) -> List(Instance)

/// Roblox: `GenerationService.GetFullName`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetFullName
@luau.method("GetFullName")
pub fn get_full_name(instance: GenerationService) -> String

/// Roblox: `GenerationService.GetStyled`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetStyled
@luau.method("GetStyled")
pub fn get_styled(instance: GenerationService, name: String, selector: Option(String)) -> Dynamic

/// Roblox: `GenerationService.GetStyledPropertyChangedSignal`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetStyledPropertyChangedSignal
@luau.method("GetStyledPropertyChangedSignal")
pub fn get_styled_property_changed_signal(instance: GenerationService, property: String) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.GetTags`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetTags
@luau.method("GetTags")
pub fn get_tags(instance: GenerationService) -> List(Dynamic)

/// Roblox: `GenerationService.HasTag`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#HasTag
@luau.method("HasTag")
pub fn has_tag(instance: GenerationService, tag: String) -> Bool

/// Roblox: `GenerationService.IsAncestorOf`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#IsAncestorOf
@luau.method("IsAncestorOf")
pub fn is_ancestor_of(instance: GenerationService, descendant: Instance) -> Bool

/// Roblox: `GenerationService.IsDescendantOf`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#IsDescendantOf
@luau.method("IsDescendantOf")
pub fn is_descendant_of(instance: GenerationService, ancestor: Instance) -> Bool

/// Roblox: `GenerationService.IsPropertyModified`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#IsPropertyModified
@luau.method("IsPropertyModified")
pub fn is_property_modified(instance: GenerationService, property: String) -> Bool

/// Roblox: `GenerationService.QueryDescendants`
/// ThreadSafety: Unsafe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#QueryDescendants
@luau.method("QueryDescendants")
pub fn query_descendants(instance: GenerationService, selector: String) -> List(Instance)

/// Roblox: `GenerationService.RemoveTag`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#RemoveTag
@luau.method("RemoveTag")
pub fn remove_tag(instance: GenerationService, tag: String) -> Nil

/// Roblox: `GenerationService.ResetPropertyToDefault`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#ResetPropertyToDefault
@luau.method("ResetPropertyToDefault")
pub fn reset_property_to_default(instance: GenerationService, property: String) -> Nil

/// Roblox: `GenerationService.SetAttribute`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#SetAttribute
@luau.method("SetAttribute")
pub fn set_attribute(instance: GenerationService, attribute: String, value: Dynamic) -> Nil

/// Roblox: `GenerationService.WaitForChild`
/// ThreadSafety: Unsafe
/// Tags: CustomLuaState, CanYield
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#WaitForChild
@luau.method("WaitForChild")
pub fn wait_for_child(instance: GenerationService, child_name: String, time_out: OptionDouble) -> Instance

/// Roblox: `GenerationService.AncestryChanged`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#AncestryChanged
@luau.event("AncestryChanged")
pub fn ancestry_changed(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.AttributeChanged`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#AttributeChanged
@luau.event("AttributeChanged")
pub fn attribute_changed(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.ChildAdded`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#ChildAdded
@luau.event("ChildAdded")
pub fn child_added(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.ChildRemoved`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#ChildRemoved
@luau.event("ChildRemoved")
pub fn child_removed(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.DescendantAdded`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#DescendantAdded
@luau.event("DescendantAdded")
pub fn descendant_added(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.DescendantRemoving`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#DescendantRemoving
@luau.event("DescendantRemoving")
pub fn descendant_removing(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.Destroying`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Destroying
@luau.event("Destroying")
pub fn destroying(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.StyledPropertiesChanged`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#StyledPropertiesChanged
@luau.event("StyledPropertiesChanged")
pub fn styled_properties_changed(instance: GenerationService) -> RBXScriptSignal(Dynamic)

/// Gets Roblox property `GenerationService.ClassName`.
///
/// Roblox: `GenerationService.ClassName`
/// ThreadSafety: ReadSafe
/// Tags: ReadOnly, NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#ClassName
@luau.property("ClassName")
pub fn get_class_name(instance: GenerationService) -> String

/// Roblox: `GenerationService.GetPropertyChangedSignal`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#GetPropertyChangedSignal
@luau.method("GetPropertyChangedSignal")
pub fn get_property_changed_signal(instance: GenerationService, property: String) -> RBXScriptSignal(Dynamic)

/// Roblox: `GenerationService.IsA`
/// ThreadSafety: Safe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#IsA
@luau.method("IsA")
pub fn is_a(instance: GenerationService, class_name: String) -> Bool

/// Roblox: `GenerationService.Changed`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/GenerationService#Changed
@luau.event("Changed")
pub fn changed(instance: GenerationService) -> RBXScriptSignal(Dynamic)
