// Generated class bindings for Roblox API
import roblox/dynamic.{type Dynamic}
import roblox/types.{type Instance, type Object, type TextGenerator}

/// Treats `TextGenerator` as its Roblox ancestor `Instance`.
///
/// This is an upcast only; it does not check or change the underlying Roblox object.
@luau.global("(function(x) return x end)")
pub fn as_instance(instance: TextGenerator) -> Instance

/// Treats `TextGenerator` as its Roblox ancestor `Object`.
///
/// This is an upcast only; it does not check or change the underlying Roblox object.
@luau.global("(function(x) return x end)")
pub fn as_object(instance: TextGenerator) -> Object

/// Gets Roblox property `TextGenerator.Seed`.
///
/// Sets a fixed seed for the random number generator, allowing reproducible responses in cases where the same input parameters are used across multiple requests.
///
/// Roblox: `TextGenerator.Seed`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Seed
@luau.property("Seed")
pub fn get_seed(instance: TextGenerator) -> Int

/// Sets Roblox property `TextGenerator.Seed`.
///
/// Sets a fixed seed for the random number generator, allowing reproducible responses in cases where the same input parameters are used across multiple requests.
///
/// Roblox: `TextGenerator.Seed`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Seed
@luau.set_property("Seed")
pub fn set_seed(instance: TextGenerator, value: Int) -> TextGenerator

/// Gets Roblox property `TextGenerator.SystemPrompt`.
///
/// Provides context to the model about its role, tone, or behavior during conversation.
///
/// Roblox: `TextGenerator.SystemPrompt`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#SystemPrompt
@luau.property("SystemPrompt")
pub fn get_system_prompt(instance: TextGenerator) -> String

/// Sets Roblox property `TextGenerator.SystemPrompt`.
///
/// Provides context to the model about its role, tone, or behavior during conversation.
///
/// Roblox: `TextGenerator.SystemPrompt`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#SystemPrompt
@luau.set_property("SystemPrompt")
pub fn set_system_prompt(instance: TextGenerator, value: String) -> TextGenerator

/// Gets Roblox property `TextGenerator.Temperature`.
///
/// Controls the "creativity" or randomness of the model's responses.
///
/// Roblox: `TextGenerator.Temperature`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Temperature
@luau.property("Temperature")
pub fn get_temperature(instance: TextGenerator) -> Float

/// Sets Roblox property `TextGenerator.Temperature`.
///
/// Controls the "creativity" or randomness of the model's responses.
///
/// Roblox: `TextGenerator.Temperature`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Temperature
@luau.set_property("Temperature")
pub fn set_temperature(instance: TextGenerator, value: Float) -> TextGenerator

/// Gets Roblox property `TextGenerator.TopP`.
///
/// Helps the AI model narrow or expand the range of possible words to sample from while generating the next token.
///
/// Roblox: `TextGenerator.TopP`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#TopP
@luau.property("TopP")
pub fn get_top_p(instance: TextGenerator) -> Float

/// Sets Roblox property `TextGenerator.TopP`.
///
/// Helps the AI model narrow or expand the range of possible words to sample from while generating the next token.
///
/// Roblox: `TextGenerator.TopP`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#TopP
@luau.set_property("TopP")
pub fn set_top_p(instance: TextGenerator, value: Float) -> TextGenerator

/// Returns text generated by an LLM based on the provided system and user prompts.
///
/// Roblox: `TextGenerator.GenerateTextAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GenerateTextAsync
///
/// Parameters:
/// - `instance`: Gives access to a large language model for text generation.
/// - `request`: A dictionary containing optional parameters for the text generation request. The currently supported parameters are UserPrompt, ContextToken, and MaxTokens.
///
/// Returns:
/// - A dictionary containing the generated response.
@luau.method("GenerateTextAsync")
pub fn generate_text_async(instance: TextGenerator, request: Dynamic) -> Dynamic
