// Generated class bindings for Roblox API
import roblox/option.{type Option}
import roblox/signal.{type RBXScriptSignal}
import roblox/dynamic.{type Dynamic}
import roblox/types.{type Actor, type Instance, type OptionDouble, type OptionInt64, type SecurityCapabilities, type TextGenerator, type UniqueId}

/// Gets Roblox property `TextGenerator.Seed`.
///
/// Sets a fixed seed for the random number generator, allowing reproducible responses in cases where the same input parameters are used across multiple requests.
///
/// Roblox: `TextGenerator.Seed`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Seed
@luau.property("Seed")
pub fn get_seed(instance: TextGenerator) -> Int

/// Sets Roblox property `TextGenerator.Seed`.
///
/// Sets a fixed seed for the random number generator, allowing reproducible responses in cases where the same input parameters are used across multiple requests.
///
/// Roblox: `TextGenerator.Seed`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Seed
@luau.set_property("Seed")
pub fn set_seed(instance: TextGenerator, value: Int) -> TextGenerator

/// Gets Roblox property `TextGenerator.SystemPrompt`.
///
/// Provides context to the model about its role, tone, or behavior during conversation.
///
/// Roblox: `TextGenerator.SystemPrompt`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#SystemPrompt
@luau.property("SystemPrompt")
pub fn get_system_prompt(instance: TextGenerator) -> String

/// Sets Roblox property `TextGenerator.SystemPrompt`.
///
/// Provides context to the model about its role, tone, or behavior during conversation.
///
/// Roblox: `TextGenerator.SystemPrompt`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#SystemPrompt
@luau.set_property("SystemPrompt")
pub fn set_system_prompt(instance: TextGenerator, value: String) -> TextGenerator

/// Gets Roblox property `TextGenerator.Temperature`.
///
/// Controls the "creativity" or randomness of the model's responses.
///
/// Roblox: `TextGenerator.Temperature`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Temperature
@luau.property("Temperature")
pub fn get_temperature(instance: TextGenerator) -> Float

/// Sets Roblox property `TextGenerator.Temperature`.
///
/// Controls the "creativity" or randomness of the model's responses.
///
/// Roblox: `TextGenerator.Temperature`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Temperature
@luau.set_property("Temperature")
pub fn set_temperature(instance: TextGenerator, value: Float) -> TextGenerator

/// Gets Roblox property `TextGenerator.TopP`.
///
/// Helps the AI model narrow or expand the range of possible words to sample from while generating the next token.
///
/// Roblox: `TextGenerator.TopP`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#TopP
@luau.property("TopP")
pub fn get_top_p(instance: TextGenerator) -> Float

/// Sets Roblox property `TextGenerator.TopP`.
///
/// Helps the AI model narrow or expand the range of possible words to sample from while generating the next token.
///
/// Roblox: `TextGenerator.TopP`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#TopP
@luau.set_property("TopP")
pub fn set_top_p(instance: TextGenerator, value: Float) -> TextGenerator

/// Returns text generated by an LLM based on the provided system and user prompts.
///
/// Roblox: `TextGenerator.GenerateTextAsync`
/// ThreadSafety: Unsafe
/// Tags: Yields
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GenerateTextAsync
///
/// Parameters:
/// - `instance`: Gives access to a large language model for text generation.
/// - `request`: A dictionary containing optional parameters for the text generation request. The currently supported parameters are UserPrompt, ContextToken, and MaxTokens.
///
/// Returns:
/// - A dictionary containing the generated response.
@luau.method("GenerateTextAsync")
pub fn generate_text_async(instance: TextGenerator, request: Dynamic) -> Dynamic

/// Gets Roblox property `TextGenerator.Archivable`.
///
/// Roblox: `TextGenerator.Archivable`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Archivable
@luau.property("Archivable")
pub fn get_archivable(instance: TextGenerator) -> Bool

/// Sets Roblox property `TextGenerator.Archivable`.
///
/// Roblox: `TextGenerator.Archivable`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Archivable
@luau.set_property("Archivable")
pub fn set_archivable(instance: TextGenerator, value: Bool) -> TextGenerator

/// Gets Roblox property `TextGenerator.Capabilities`.
///
/// Roblox: `TextGenerator.Capabilities`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Capabilities
@luau.property("Capabilities")
pub fn get_capabilities(instance: TextGenerator) -> SecurityCapabilities

/// Sets Roblox property `TextGenerator.Capabilities`.
///
/// Roblox: `TextGenerator.Capabilities`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Capabilities
@luau.set_property("Capabilities")
pub fn set_capabilities(instance: TextGenerator, value: SecurityCapabilities) -> TextGenerator

/// Gets Roblox property `TextGenerator.Name`.
///
/// Roblox: `TextGenerator.Name`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Name
@luau.property("Name")
pub fn get_name(instance: TextGenerator) -> String

/// Sets Roblox property `TextGenerator.Name`.
///
/// Roblox: `TextGenerator.Name`
/// ThreadSafety: ReadSafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Name
@luau.set_property("Name")
pub fn set_name(instance: TextGenerator, value: String) -> TextGenerator

/// Gets Roblox property `TextGenerator.Parent`.
///
/// Roblox: `TextGenerator.Parent`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Parent
@luau.property("Parent")
pub fn get_parent(instance: TextGenerator) -> Instance

/// Sets Roblox property `TextGenerator.Parent`.
///
/// Roblox: `TextGenerator.Parent`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Parent
@luau.set_property("Parent")
pub fn set_parent(instance: TextGenerator, value: Instance) -> TextGenerator

/// Gets Roblox property `TextGenerator.RobloxLocked`.
///
/// Roblox: `TextGenerator.RobloxLocked`
/// ThreadSafety: ReadSafe
/// Tags: Hidden
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#RobloxLocked
@luau.property("RobloxLocked")
pub fn get_roblox_locked(instance: TextGenerator) -> Bool

/// Gets Roblox property `TextGenerator.Sandboxed`.
///
/// Roblox: `TextGenerator.Sandboxed`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Sandboxed
@luau.property("Sandboxed")
pub fn get_sandboxed(instance: TextGenerator) -> Bool

/// Sets Roblox property `TextGenerator.Sandboxed`.
///
/// Roblox: `TextGenerator.Sandboxed`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Sandboxed
@luau.set_property("Sandboxed")
pub fn set_sandboxed(instance: TextGenerator, value: Bool) -> TextGenerator

/// Gets Roblox property `TextGenerator.SourceAssetId`.
///
/// Roblox: `TextGenerator.SourceAssetId`
/// ThreadSafety: ReadSafe
/// Tags: Hidden
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#SourceAssetId
@luau.property("SourceAssetId")
pub fn get_source_asset_id(instance: TextGenerator) -> OptionInt64

/// Gets Roblox property `TextGenerator.UniqueId`.
///
/// Roblox: `TextGenerator.UniqueId`
/// ThreadSafety: ReadSafe
/// Tags: NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#UniqueId
@luau.property("UniqueId")
pub fn get_unique_id(instance: TextGenerator) -> UniqueId

/// Roblox: `TextGenerator.AddTag`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#AddTag
@luau.method("AddTag")
pub fn add_tag(instance: TextGenerator, tag: String) -> Nil

/// Roblox: `TextGenerator.ClearAllChildren`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#ClearAllChildren
@luau.method("ClearAllChildren")
pub fn clear_all_children(instance: TextGenerator) -> Nil

/// Roblox: `TextGenerator.Clone`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Clone
@luau.method("Clone")
pub fn clone(instance: TextGenerator) -> Instance

/// Roblox: `TextGenerator.Destroy`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Destroy
@luau.method("Destroy")
pub fn destroy(instance: TextGenerator) -> Nil

/// Roblox: `TextGenerator.FindFirstAncestor`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstAncestor
@luau.method("FindFirstAncestor")
pub fn find_first_ancestor(instance: TextGenerator, name: String) -> Option(Instance)

/// Roblox: `TextGenerator.FindFirstAncestorOfClass`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstAncestorOfClass
@luau.method("FindFirstAncestorOfClass")
pub fn find_first_ancestor_of_class(instance: TextGenerator, class_name: String) -> Option(Instance)

/// Roblox: `TextGenerator.FindFirstAncestorWhichIsA`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstAncestorWhichIsA
@luau.method("FindFirstAncestorWhichIsA")
pub fn find_first_ancestor_which_is_a(instance: TextGenerator, class_name: String) -> Option(Instance)

/// Roblox: `TextGenerator.FindFirstChild`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstChild
@luau.method("FindFirstChild")
pub fn find_first_child(instance: TextGenerator, name: String, recursive: Bool) -> Option(Instance)

/// Roblox: `TextGenerator.FindFirstChildOfClass`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstChildOfClass
@luau.method("FindFirstChildOfClass")
pub fn find_first_child_of_class(instance: TextGenerator, class_name: String) -> Option(Instance)

/// Roblox: `TextGenerator.FindFirstChildWhichIsA`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstChildWhichIsA
@luau.method("FindFirstChildWhichIsA")
pub fn find_first_child_which_is_a(instance: TextGenerator, class_name: String, recursive: Bool) -> Option(Instance)

/// Roblox: `TextGenerator.FindFirstDescendant`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#FindFirstDescendant
@luau.method("FindFirstDescendant")
pub fn find_first_descendant(instance: TextGenerator, name: String) -> Option(Instance)

/// Roblox: `TextGenerator.GetActor`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetActor
@luau.method("GetActor")
pub fn get_actor(instance: TextGenerator) -> Actor

/// Roblox: `TextGenerator.GetAttribute`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetAttribute
@luau.method("GetAttribute")
pub fn get_attribute(instance: TextGenerator, attribute: String) -> Dynamic

/// Roblox: `TextGenerator.GetAttributeChangedSignal`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetAttributeChangedSignal
@luau.method("GetAttributeChangedSignal")
pub fn get_attribute_changed_signal(instance: TextGenerator, attribute: String) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.GetAttributes`
/// ThreadSafety: Safe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetAttributes
@luau.method("GetAttributes")
pub fn get_attributes(instance: TextGenerator) -> Dynamic

/// Roblox: `TextGenerator.GetChildren`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetChildren
@luau.method("GetChildren")
pub fn get_children(instance: TextGenerator) -> List(Instance)

/// Roblox: `TextGenerator.GetDescendants`
/// ThreadSafety: Safe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetDescendants
@luau.method("GetDescendants")
pub fn get_descendants(instance: TextGenerator) -> List(Instance)

/// Roblox: `TextGenerator.GetFullName`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetFullName
@luau.method("GetFullName")
pub fn get_full_name(instance: TextGenerator) -> String

/// Roblox: `TextGenerator.GetStyled`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetStyled
@luau.method("GetStyled")
pub fn get_styled(instance: TextGenerator, name: String, selector: Option(String)) -> Dynamic

/// Roblox: `TextGenerator.GetStyledPropertyChangedSignal`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetStyledPropertyChangedSignal
@luau.method("GetStyledPropertyChangedSignal")
pub fn get_styled_property_changed_signal(instance: TextGenerator, property: String) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.GetTags`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetTags
@luau.method("GetTags")
pub fn get_tags(instance: TextGenerator) -> List(Dynamic)

/// Roblox: `TextGenerator.HasTag`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#HasTag
@luau.method("HasTag")
pub fn has_tag(instance: TextGenerator, tag: String) -> Bool

/// Roblox: `TextGenerator.IsAncestorOf`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#IsAncestorOf
@luau.method("IsAncestorOf")
pub fn is_ancestor_of(instance: TextGenerator, descendant: Instance) -> Bool

/// Roblox: `TextGenerator.IsDescendantOf`
/// ThreadSafety: Safe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#IsDescendantOf
@luau.method("IsDescendantOf")
pub fn is_descendant_of(instance: TextGenerator, ancestor: Instance) -> Bool

/// Roblox: `TextGenerator.IsPropertyModified`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#IsPropertyModified
@luau.method("IsPropertyModified")
pub fn is_property_modified(instance: TextGenerator, property: String) -> Bool

/// Roblox: `TextGenerator.QueryDescendants`
/// ThreadSafety: Unsafe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#QueryDescendants
@luau.method("QueryDescendants")
pub fn query_descendants(instance: TextGenerator, selector: String) -> List(Instance)

/// Roblox: `TextGenerator.RemoveTag`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#RemoveTag
@luau.method("RemoveTag")
pub fn remove_tag(instance: TextGenerator, tag: String) -> Nil

/// Roblox: `TextGenerator.ResetPropertyToDefault`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#ResetPropertyToDefault
@luau.method("ResetPropertyToDefault")
pub fn reset_property_to_default(instance: TextGenerator, property: String) -> Nil

/// Roblox: `TextGenerator.SetAttribute`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#SetAttribute
@luau.method("SetAttribute")
pub fn set_attribute(instance: TextGenerator, attribute: String, value: Dynamic) -> Nil

/// Roblox: `TextGenerator.WaitForChild`
/// ThreadSafety: Unsafe
/// Tags: CustomLuaState, CanYield
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#WaitForChild
@luau.method("WaitForChild")
pub fn wait_for_child(instance: TextGenerator, child_name: String, time_out: OptionDouble) -> Instance

/// Roblox: `TextGenerator.AncestryChanged`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#AncestryChanged
@luau.event("AncestryChanged")
pub fn ancestry_changed(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.AttributeChanged`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#AttributeChanged
@luau.event("AttributeChanged")
pub fn attribute_changed(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.ChildAdded`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#ChildAdded
@luau.event("ChildAdded")
pub fn child_added(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.ChildRemoved`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#ChildRemoved
@luau.event("ChildRemoved")
pub fn child_removed(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.DescendantAdded`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#DescendantAdded
@luau.event("DescendantAdded")
pub fn descendant_added(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.DescendantRemoving`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#DescendantRemoving
@luau.event("DescendantRemoving")
pub fn descendant_removing(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.Destroying`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Destroying
@luau.event("Destroying")
pub fn destroying(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.StyledPropertiesChanged`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#StyledPropertiesChanged
@luau.event("StyledPropertiesChanged")
pub fn styled_properties_changed(instance: TextGenerator) -> RBXScriptSignal(Dynamic)

/// Gets Roblox property `TextGenerator.ClassName`.
///
/// Roblox: `TextGenerator.ClassName`
/// ThreadSafety: ReadSafe
/// Tags: ReadOnly, NotReplicated
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#ClassName
@luau.property("ClassName")
pub fn get_class_name(instance: TextGenerator) -> String

/// Roblox: `TextGenerator.GetPropertyChangedSignal`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#GetPropertyChangedSignal
@luau.method("GetPropertyChangedSignal")
pub fn get_property_changed_signal(instance: TextGenerator, property: String) -> RBXScriptSignal(Dynamic)

/// Roblox: `TextGenerator.IsA`
/// ThreadSafety: Safe
/// Tags: CustomLuaState
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#IsA
@luau.method("IsA")
pub fn is_a(instance: TextGenerator, class_name: String) -> Bool

/// Roblox: `TextGenerator.Changed`
/// ThreadSafety: Unsafe
/// See: https://create.roblox.com/docs/reference/engine/classes/TextGenerator#Changed
@luau.event("Changed")
pub fn changed(instance: TextGenerator) -> RBXScriptSignal(Dynamic)
