// Generated types for Roblox API

pub opaque type AccessModifierType
pub opaque type Accessory
pub opaque type AccessoryDescription
pub opaque type AccessoryType
pub opaque type AccountService
pub opaque type Accoutrement
pub opaque type AchievementService
pub opaque type ActionOnAutoResumeSync
pub opaque type ActionOnStopSync
pub opaque type ActivityHistoryEventService
pub opaque type Actor
pub opaque type ActuatorRelativeTo
pub opaque type ActuatorType
pub opaque type AdFormat
pub opaque type AdGui
pub opaque type AdPortal
pub opaque type AdReward
pub opaque type AdService
pub opaque type AdShape
pub opaque type AdTeleportMethod
pub opaque type AdUIEventType
pub opaque type AdUnitStatus
pub opaque type AdornCullingMode
pub opaque type AdornShading
pub opaque type AdvancedDragger
pub opaque type AirController
pub opaque type AlignOrientation
pub opaque type AlignPosition
pub opaque type AlignType
pub opaque type AlphaMode
pub opaque type AnalyticsEconomyAction
pub opaque type AnalyticsEconomyFlowType
pub opaque type AnalyticsLogLevel
pub opaque type AnalyticsProgressionStatus
pub opaque type AnalyticsProgressionType
pub opaque type AnalyticsService
pub opaque type AngularVelocity
pub opaque type Animation
pub opaque type AnimationClip
pub opaque type AnimationClipProvider
pub opaque type AnimationConstraint
pub opaque type AnimationController
pub opaque type AnimationFromVideoCreatorService
pub opaque type AnimationFromVideoCreatorStudioService
pub opaque type AnimationGraphDefinition
pub opaque type AnimationImportData
pub opaque type AnimationNode
pub opaque type AnimationNodeDefinition
pub opaque type AnimationNodeType
pub opaque type AnimationPriority
pub opaque type AnimationRigData
pub opaque type AnimationStreamTrack
pub opaque type AnimationTrack
pub opaque type Animator
pub opaque type AnimatorRetargetingMode
pub opaque type Annotation
pub opaque type AnnotationChannelContentPreference
pub opaque type AnnotationEditingMode
pub opaque type AnnotationPlaceContentPreference
pub opaque type AnnotationRequestStatus
pub opaque type AnnotationsService
pub opaque type AntiAliasing
pub opaque type AppAgeSignalsService
pub opaque type AppLifecycleManagerState
pub opaque type AppLifecycleObserverService
pub opaque type AppRatingPromptService
pub opaque type AppShellActionType
pub opaque type AppShellFeature
pub opaque type AppStorageService
pub opaque type AppUpdateService
pub opaque type ApplyStrokeMode
pub opaque type ArcHandles
pub opaque type Array?
pub opaque type AspectType
pub opaque type AssetCounterService
pub opaque type AssetCreatorType
pub opaque type AssetDeliveryProxy
pub opaque type AssetFetchStatus
pub opaque type AssetImportService
pub opaque type AssetImportSession
pub opaque type AssetManagerService
pub opaque type AssetPatchSettings
pub opaque type AssetQualityService
pub opaque type AssetRepresentation
pub opaque type AssetService
pub opaque type AssetSoundEffect
pub opaque type AssetType
pub opaque type AssetTypeVerification
pub opaque type Atmosphere
pub opaque type AtmosphereSensor
pub opaque type Attachment
pub opaque type AudioAnalyzer
pub opaque type AudioApiRollout
pub opaque type AudioChannelLayout
pub opaque type AudioChannelMixer
pub opaque type AudioChannelSplitter
pub opaque type AudioChorus
pub opaque type AudioCompressor
pub opaque type AudioDeviceInput
pub opaque type AudioDeviceOutput
pub opaque type AudioDistortion
pub opaque type AudioEcho
pub opaque type AudioEmitter
pub opaque type AudioEqualizer
pub opaque type AudioFader
pub opaque type AudioFilter
pub opaque type AudioFilterType
pub opaque type AudioFlanger
pub opaque type AudioFocusService
pub opaque type AudioGate
pub opaque type AudioLimiter
pub opaque type AudioListener
pub opaque type AudioPages
pub opaque type AudioPitchShifter
pub opaque type AudioPlayer
pub opaque type AudioRecorder
pub opaque type AudioReverb
pub opaque type AudioSearchParams
pub opaque type AudioSimulationFidelity
pub opaque type AudioSpeechToText
pub opaque type AudioSubType
pub opaque type AudioTextToSpeech
pub opaque type AudioTremolo
pub opaque type AudioWindowSize
pub opaque type AuroraScript
pub opaque type AuroraScriptObject
pub opaque type AuthorityMode
pub opaque type AutoIndentRule
pub opaque type AutomaticSize
pub opaque type AvatarAbilityRules
pub opaque type AvatarAccessoryRules
pub opaque type AvatarAnimationRules
pub opaque type AvatarAssetType
pub opaque type AvatarBodyRules
pub opaque type AvatarChatService
pub opaque type AvatarChatServiceFeature
pub opaque type AvatarClothingRules
pub opaque type AvatarCollisionRules
pub opaque type AvatarCreationService
pub opaque type AvatarEditorService
pub opaque type AvatarImportService
pub opaque type AvatarItemType
pub opaque type AvatarRules
pub opaque type AvatarSettings
pub opaque type AvatarSettingsAccessoryLimitMethod
pub opaque type AvatarSettingsAccessoryMode
pub opaque type AvatarSettingsAnimationClipsMode
pub opaque type AvatarSettingsAnimationPacksMode
pub opaque type AvatarSettingsAppearanceMode
pub opaque type AvatarSettingsBuildMode
pub opaque type AvatarSettingsCharacterControllerMode
pub opaque type AvatarSettingsClothingMode
pub opaque type AvatarSettingsCollisionMode
pub opaque type AvatarSettingsCustomAccessoryMode
pub opaque type AvatarSettingsCustomBodyType
pub opaque type AvatarSettingsCustomClothingMode
pub opaque type AvatarSettingsHitAndTouchDetectionMode
pub opaque type AvatarSettingsLegacyCollisionMode
pub opaque type AvatarSettingsScaleMode
pub opaque type AvatarThumbnailCustomizationType
pub opaque type AvatarUnificationMode
pub opaque type Axes
pub opaque type Axis
pub opaque type Backpack
pub opaque type BackpackItem
pub opaque type BadgeService
pub opaque type BallSocketConstraint
pub opaque type BanHistoryPages
pub opaque type BaseCoreGuiConfiguration
pub opaque type BaseImportData
pub opaque type BasePart
pub opaque type BasePlayerGui
pub opaque type BaseRemoteEvent
pub opaque type BaseScript
pub opaque type BaseWrap
pub opaque type Beam
pub opaque type BevelMesh
pub opaque type BillboardGui
pub opaque type BinType
pub opaque type BinaryString
pub opaque type BinaryStringValue
pub opaque type BindableEvent
pub opaque type BindableFunction
pub opaque type BlockMesh
pub opaque type BloomEffect
pub opaque type BlurEffect
pub opaque type BodyAngularVelocity
pub opaque type BodyColors
pub opaque type BodyForce
pub opaque type BodyGyro
pub opaque type BodyMover
pub opaque type BodyPart
pub opaque type BodyPartDescription
pub opaque type BodyPartR15
pub opaque type BodyPosition
pub opaque type BodyThrust
pub opaque type BodyVelocity
pub opaque type Bone
pub opaque type BoolValue
pub opaque type BorderMode
pub opaque type BorderStrokePosition
pub opaque type BoxHandleAdornment
pub opaque type Breakpoint
pub opaque type BrickColor
pub opaque type BrickColorValue
pub opaque type BrowserService
pub opaque type BubbleChatConfiguration
pub opaque type BubbleChatMessageProperties
pub opaque type BugReporterService
pub opaque type BulkImportService
pub opaque type BulkMoveMode
pub opaque type BuoyancySensor
pub opaque type Button
pub opaque type ButtonStyle
pub opaque type CFrame
pub opaque type CFrameValue
pub opaque type CSGDictionaryService
pub opaque type CacheableContentProvider
pub opaque type CageType
pub opaque type CalloutService
pub opaque type Camera
pub opaque type CameraMode
pub opaque type CameraNavigationModel
pub opaque type CameraPanMode
pub opaque type CameraSpeedAdjustBinding
pub opaque type CameraType
pub opaque type CanvasGroup
pub opaque type Capture
pub opaque type CaptureGalleryPermission
pub opaque type CaptureService
pub opaque type CaptureType
pub opaque type CapturesPages
pub opaque type CapturesViewConfiguration
pub opaque type CatalogPages
pub opaque type CatalogSearchParams
pub opaque type CellBlock
pub opaque type CellMaterial
pub opaque type CellOrientation
pub opaque type CenterDialogType
pub opaque type ChangeHistoryService
pub opaque type ChangeHistoryStreamingService
pub opaque type ChannelSelectorSoundEffect
pub opaque type ChannelTabsConfiguration
pub opaque type CharacterAppearance
pub opaque type CharacterControlMode
pub opaque type CharacterMesh
pub opaque type Chat
pub opaque type ChatCallbackType
pub opaque type ChatColor
pub opaque type ChatInputBarConfiguration
pub opaque type ChatMode
pub opaque type ChatRestrictionStatus
pub opaque type ChatStyle
pub opaque type ChatVersion
pub opaque type ChatWindowConfiguration
pub opaque type ChatWindowMessageProperties
pub opaque type ChorusSoundEffect
pub opaque type ClickDetector
pub opaque type ClientAnimatorThrottlingMode
pub opaque type ClientReplicator
pub opaque type ClimbController
pub opaque type ClipEvaluator
pub opaque type Clothing
pub opaque type CloudCRUDService
pub opaque type CloudExecutionService
pub opaque type CloudLocalizationTable
pub opaque type Clouds
pub opaque type ClusterPacketCache
pub opaque type Collaborator
pub opaque type CollaboratorStatus
pub opaque type CollaboratorsService
pub opaque type CollectionService
pub opaque type CollisionFidelity
pub opaque type Color3
pub opaque type Color3?
pub opaque type Color3Value
pub opaque type ColorCorrectionEffect
pub opaque type ColorGradingEffect
pub opaque type ColorSequence
pub opaque type CommerceService
pub opaque type CompileTarget
pub opaque type CompletionAcceptanceBehavior
pub opaque type CompositeValueCurve
pub opaque type CompositeValueCurveType
pub opaque type CompressionAlgorithm
pub opaque type CompressorSoundEffect
pub opaque type ComputerCameraMovementMode
pub opaque type ComputerMovementMode
pub opaque type ConeHandleAdornment
pub opaque type ConfigService
pub opaque type ConfigSnapshot
pub opaque type ConfigSnapshotErrorState
pub opaque type Configuration
pub opaque type ConfigureServerService
pub opaque type ConnectionError
pub opaque type ConnectivityService
pub opaque type Constraint
pub opaque type Content
pub opaque type ContentId
pub opaque type ContentProvider
pub opaque type ContextActionService
pub opaque type ControlMode
pub opaque type Controller
pub opaque type ControllerBase
pub opaque type ControllerManager
pub opaque type ControllerPartSensor
pub opaque type ControllerSensor
pub opaque type ControllerService
pub opaque type CookiesService
pub opaque type CoordinateFrame?
pub opaque type CoreGui
pub opaque type CoreGuiConfiguration
pub opaque type CoreGuiType
pub opaque type CorePackages
pub opaque type CoreScript
pub opaque type CoreScriptDebuggingManagerHelper
pub opaque type CoreScriptSyncService
pub opaque type CornerWedgePart
pub opaque type CreationDBService
pub opaque type CreatorStoreService
pub opaque type CreatorType
pub opaque type CrossDMScriptChangeListener
pub opaque type CurrencyType
pub opaque type CurveAnimation
pub opaque type CustomCameraMode
pub opaque type CustomEvent
pub opaque type CustomEventReceiver
pub opaque type CustomLog
pub opaque type CustomSoundEffect
pub opaque type CylinderHandleAdornment
pub opaque type CylinderMesh
pub opaque type CylindricalConstraint
pub opaque type DataModel
pub opaque type DataModelMesh
pub opaque type DataModelPatchService
pub opaque type DataModelSession
pub opaque type DataStore
pub opaque type DataStoreGetOptions
pub opaque type DataStoreIncrementOptions
pub opaque type DataStoreInfo
pub opaque type DataStoreKey
pub opaque type DataStoreKeyInfo
pub opaque type DataStoreKeyPages
pub opaque type DataStoreListingPages
pub opaque type DataStoreObjectVersionInfo
pub opaque type DataStoreOptions
pub opaque type DataStorePages
pub opaque type DataStoreRequestType
pub opaque type DataStoreService
pub opaque type DataStoreSetOptions
pub opaque type DataStoreVersionPages
pub opaque type DateTime
pub opaque type Debris
pub opaque type DebugBreakModeType
pub opaque type DebugSettings
pub opaque type DebuggablePluginWatcher
pub opaque type DebuggerBreakpoint
pub opaque type DebuggerConnection
pub opaque type DebuggerConnectionManager
pub opaque type DebuggerExceptionBreakMode
pub opaque type DebuggerFrameType
pub opaque type DebuggerLuaResponse
pub opaque type DebuggerManager
pub opaque type DebuggerPauseReason
pub opaque type DebuggerStatus
pub opaque type DebuggerUIService
pub opaque type DebuggerVariable
pub opaque type DebuggerWatch
pub opaque type Decal
pub opaque type DefaultScriptSyncFileType
pub opaque type DeferredAssetManagerService
pub opaque type DepthOfFieldEffect
pub opaque type DevCameraOcclusionMode
pub opaque type DevComputerCameraMovementMode
pub opaque type DevComputerMovementMode
pub opaque type DevTouchCameraMovementMode
pub opaque type DevTouchMovementMode
pub opaque type DeveloperMemoryTag
pub opaque type DeviceFeatureType
pub opaque type DeviceIdService
pub opaque type DeviceLevel
pub opaque type DeviceSimulatorScalingMode
pub opaque type DeviceType
pub opaque type Dialog
pub opaque type DialogBehaviorType
pub opaque type DialogChoice
pub opaque type DialogPurpose
pub opaque type DialogTone
pub opaque type Dictionary?
pub opaque type DigitsRigDescription
pub opaque type DigitsRigDescriptionSide
pub opaque type DisplayScalingMode
pub opaque type DisplaySize
pub opaque type DistortionSoundEffect
pub opaque type DockWidgetPluginGui
pub opaque type DockWidgetPluginGuiInfo
pub opaque type DominantAxis
pub opaque type DoubleConstrainedValue
pub opaque type DraftStatusCode
pub opaque type DraftsService
pub opaque type DragDetector
pub opaque type DragDetectorDragStyle
pub opaque type DragDetectorPermissionPolicy
pub opaque type DragDetectorResponseStyle
pub opaque type Dragger
pub opaque type DraggerCoordinateSpace
pub opaque type DraggerMovementMode
pub opaque type DraggerService
pub opaque type DraggingScrollBar
pub opaque type DynamicRotate
pub opaque type EasingDirection
pub opaque type EasingStyle
pub opaque type EchoSoundEffect
pub opaque type EditableImage
pub opaque type EditableMesh
pub opaque type EditableService
pub opaque type ElasticBehavior
pub opaque type EncodingService
pub opaque type EngineFolder
pub opaque type EnviromentalPhysicsThrottle
pub opaque type EqualizerSoundEffect
pub opaque type EulerRotationCurve
pub opaque type EventIngestService
pub opaque type ExampleV2Service
pub opaque type ExecutedRemoteCommand
pub opaque type ExperienceAuthService
pub opaque type ExperienceInviteOptions
pub opaque type ExperienceNotificationService
pub opaque type ExperienceService
pub opaque type ExperienceStateCaptureSelectionMode
pub opaque type ExperienceStateCaptureService
pub opaque type ExperienceStateRecordingLoadMode
pub opaque type ExperienceStateRecordingLoadSourceType
pub opaque type ExperienceStateRecordingPlaybackMode
pub opaque type ExperienceStateRecordingService
pub opaque type ExplorerFilter
pub opaque type ExplorerFilterAutocompleter
pub opaque type ExplorerServiceVisibilityService
pub opaque type Explosion
pub opaque type ExplosionType
pub opaque type ExternalEditorMode
pub opaque type FACSDataLod
pub opaque type FaceAnimatorService
pub opaque type FaceControls
pub opaque type FaceInstance
pub opaque type Faces
pub opaque type FacialAgeEstimationService
pub opaque type FacialAnimationRecordingService
pub opaque type FacialAnimationStreamingServiceStats
pub opaque type FacialAnimationStreamingServiceV2
pub opaque type FacialAnimationStreamingSubsessionStats
pub opaque type FacsActionUnit
pub opaque type FacsImportData
pub opaque type Feature
pub opaque type FeatureRestrictionManager
pub opaque type FieldOfViewMode
pub opaque type File
pub opaque type FileManagerService
pub opaque type FileMesh
pub opaque type FillDirection
pub opaque type FinishRecordingOperation
pub opaque type Fire
pub opaque type Flag
pub opaque type FlagStand
pub opaque type FlagStandService
pub opaque type FlangeSoundEffect
pub opaque type FloatCurve
pub opaque type FloatCurveKey
pub opaque type FloorWire
pub opaque type FluidFidelity
pub opaque type FluidForceSensor
pub opaque type FluidForces
pub opaque type FlyweightService
pub opaque type Folder
pub opaque type Font
pub opaque type FontSize
pub opaque type ForceField
pub opaque type ForceLimitMode
pub opaque type FormFactor
pub opaque type FormFactorPart
pub opaque type Frame
pub opaque type FrameStyle
pub opaque type FramerateManagerMode
pub opaque type FriendPages
pub opaque type FriendService
pub opaque type FriendStatus
pub opaque type Function?
pub opaque type FunctionalTest
pub opaque type GameAvatarType
pub opaque type GamePassService
pub opaque type GameSettings
pub opaque type GamepadService
pub opaque type GearGenreSetting
pub opaque type GearType
pub opaque type GeneratedFolder
pub opaque type GenerationService
pub opaque type GenericChallengeService
pub opaque type GenericSettings
pub opaque type Genre
pub opaque type Geometry
pub opaque type GeometryService
pub opaque type GetTextBoundsParams
pub opaque type GlobalDataStore
pub opaque type GlobalSettings
pub opaque type Glue
pub opaque type GongService
pub opaque type GraphicsMode
pub opaque type GraphicsOptimizationMode
pub opaque type GroundController
pub opaque type GroupImportData
pub opaque type GroupMembershipStatus
pub opaque type GroupService
pub opaque type GuiBase
pub opaque type GuiBase2d
pub opaque type GuiBase3d
pub opaque type GuiButton
pub opaque type GuiLabel
pub opaque type GuiMain
pub opaque type GuiObject
pub opaque type GuiService
pub opaque type GuiState
pub opaque type GuiType
pub opaque type GuidRegistryService
pub opaque type HSRDataContentProvider
pub opaque type HandleAdornment
pub opaque type Handles
pub opaque type HandlesBase
pub opaque type HandlesStyle
pub opaque type HapticEffect
pub opaque type HapticEffectType
pub opaque type HapticService
pub opaque type HarmonyService
pub opaque type HashAlgorithm
pub opaque type Hat
pub opaque type HeapProfilerService
pub opaque type HeatmapService
pub opaque type HeightmapImporterService
pub opaque type HiddenSurfaceRemovalAsset
pub opaque type Highlight
pub opaque type HighlightDepthMode
pub opaque type HingeConstraint
pub opaque type Hint
pub opaque type Hole
pub opaque type Hopper
pub opaque type HopperBin
pub opaque type HorizontalAlignment
pub opaque type HoverAnimateSpeed
pub opaque type HttpContentType
pub opaque type HttpRbxApiService
pub opaque type HttpRequest
pub opaque type HttpRequestType
pub opaque type HttpService
pub opaque type Humanoid
pub opaque type HumanoidCollisionType
pub opaque type HumanoidController
pub opaque type HumanoidDescription
pub opaque type HumanoidDisplayDistanceType
pub opaque type HumanoidHealthDisplayType
pub opaque type HumanoidRigDescription
pub opaque type HumanoidRigType
pub opaque type HumanoidStateType
pub opaque type IKCollisionsMode
pub opaque type IKControl
pub opaque type IKControlConstraintSupport
pub opaque type IKControlType
pub opaque type ILegacyStudioBridge
pub opaque type IXPLoadingStatus
pub opaque type IXPLoadingStatus?
pub opaque type IXPService
pub opaque type ImageButton
pub opaque type ImageCombineType
pub opaque type ImageHandleAdornment
pub opaque type ImageLabel
pub opaque type ImageScreenCaptureService
pub opaque type ImportSession
pub opaque type InOut
pub opaque type IncrementalPatchBuilder
pub opaque type InfoType
pub opaque type InputAction
pub opaque type InputActionType
pub opaque type InputBinding
pub opaque type InputContext
pub opaque type InputObject
pub opaque type InputSink
pub opaque type InputType
pub opaque type InsertService
pub opaque type Instance
pub opaque type InstanceAdornment
pub opaque type InstanceExtensionsService
pub opaque type InstanceFileSyncService
pub opaque type InstanceFileSyncStatus
pub opaque type IntConstrainedValue
pub opaque type IntValue
pub opaque type InternalMessagingService
pub opaque type InternalMessagingServiceVerifier
pub opaque type InterpolationThrottlingMode
pub opaque type IntersectOperation
pub opaque type InventoryPages
pub opaque type ItemLineAlignment
pub opaque type JointCreationMode
pub opaque type JointImportData
pub opaque type JointInstance
pub opaque type JointsService
pub opaque type KeyCode
pub opaque type KeyInterpolationMode
pub opaque type KeyboardService
pub opaque type Keyframe
pub opaque type KeyframeMarker
pub opaque type KeyframeSequence
pub opaque type KeyframeSequenceProvider
pub opaque type LSPFileSyncService
pub opaque type LanguageService
pub opaque type LayerCollector
pub opaque type LeftRight
pub opaque type LegacyStudioBridge
pub opaque type Light
pub opaque type Lighting
pub opaque type LightingStyle
pub opaque type Limb
pub opaque type LineForce
pub opaque type LineHandleAdornment
pub opaque type LineJoinMode
pub opaque type LinearVelocity
pub opaque type LinkingService
pub opaque type ListDisplayMode
pub opaque type ListenerLocation
pub opaque type ListenerType
pub opaque type LiveScriptingService
pub opaque type LiveSyncService
pub opaque type LoadCharacterLayeredClothing
pub opaque type LoadDynamicHeads
pub opaque type LocalDebuggerConnection
pub opaque type LocalScript
pub opaque type LocalStorageService
pub opaque type LocalizationService
pub opaque type LocalizationTable
pub opaque type LodDataEntity
pub opaque type LodDataService
pub opaque type LogReporterService
pub opaque type LogService
pub opaque type LoginService
pub opaque type LuaSettings
pub opaque type LuaSourceContainer
pub opaque type LuaWebService
pub opaque type LuauScriptAnalyzerService
pub opaque type LuauTypeCheckMode
pub opaque type MLModelDeliveryService
pub opaque type MLService
pub opaque type MLSession
pub opaque type MakeupDescription
pub opaque type MakeupType
pub opaque type ManualGlue
pub opaque type ManualSurfaceJointInstance
pub opaque type ManualWeld
pub opaque type MarkerCurve
pub opaque type MarketplaceBulkPurchasePromptStatus
pub opaque type MarketplaceService
pub opaque type MatchmakingService
pub opaque type MatchmakingType
pub opaque type Material
pub opaque type MaterialGenerationService
pub opaque type MaterialImportData
pub opaque type MaterialPattern
pub opaque type MaterialService
pub opaque type MaterialVariant
pub opaque type MemStorageConnection
pub opaque type MemStorageService
pub opaque type MembershipType
pub opaque type MemoryStoreHashMap
pub opaque type MemoryStoreHashMapPages
pub opaque type MemoryStoreQueue
pub opaque type MemoryStoreService
pub opaque type MemoryStoreSortedMap
pub opaque type MeshContentProvider
pub opaque type MeshImportData
pub opaque type MeshPart
pub opaque type MeshPartDetailLevel
pub opaque type MeshPartHeadsAndAccessories
pub opaque type MeshScaleUnit
pub opaque type MeshType
pub opaque type Message
pub opaque type MessageBusConnection
pub opaque type MessageBusService
pub opaque type MessageType
pub opaque type MessagingService
pub opaque type MetaBreakpoint
pub opaque type MetaBreakpointContext
pub opaque type MetaBreakpointManager
pub opaque type MicroProfilerService
pub opaque type Model
pub opaque type ModelLevelOfDetail
pub opaque type ModelStreamingBehavior
pub opaque type ModelStreamingMode
pub opaque type ModerationService
pub opaque type ModifierKey
pub opaque type ModuleScript
pub opaque type Motor
pub opaque type Motor6D
pub opaque type MotorFeature
pub opaque type Mouse
pub opaque type MouseBehavior
pub opaque type MouseService
pub opaque type MultipleDocumentInterfaceInstance
pub opaque type NameOcclusion
pub opaque type NegateOperation
pub opaque type NetworkClient
pub opaque type NetworkMarker
pub opaque type NetworkPeer
pub opaque type NetworkReplicator
pub opaque type NetworkServer
pub opaque type NetworkSettings
pub opaque type NetworkStatus
pub opaque type NoCollisionConstraint
pub opaque type Noise
pub opaque type NoiseType
pub opaque type NonReplicatedCSGDictionaryService
pub opaque type NormalId
pub opaque type NotificationService
pub opaque type NumberPose
pub opaque type NumberRange
pub opaque type NumberSequence
pub opaque type NumberValue
pub opaque type Object
pub opaque type ObjectValue
pub opaque type OmniRecommendationsService
pub opaque type OpenCloudApiV1
pub opaque type OpenCloudModel
pub opaque type OpenCloudService
pub opaque type OperationGraph
pub opaque type OrderedDataStore
pub opaque type OrientationAlignmentMode
pub opaque type OutfitPages
pub opaque type OutfitSource
pub opaque type OutfitType
pub opaque type OutputLayoutMode
pub opaque type OutputLink
pub opaque type OverlapParams
pub opaque type OverrideMouseIconBehavior
pub opaque type PVAdornment
pub opaque type PVInstance
pub opaque type PackageLink
pub opaque type PackagePermission
pub opaque type PackageService
pub opaque type PackageUIService
pub opaque type Packages
pub opaque type Pages
pub opaque type Pants
pub opaque type ParabolaAdornment
pub opaque type Part
pub opaque type PartAdornment
pub opaque type PartOperation
pub opaque type PartOperationAsset
pub opaque type PartType
pub opaque type ParticleEmitter
pub opaque type ParticleEmitterShape
pub opaque type ParticleEmitterShapeInOut
pub opaque type ParticleEmitterShapeStyle
pub opaque type ParticleFlipbookLayout
pub opaque type ParticleFlipbookMode
pub opaque type ParticleOrientation
pub opaque type PartyEmulatorService
pub opaque type PatchBundlerFileWatch
pub opaque type PatchMapping
pub opaque type Path
pub opaque type Path2D
pub opaque type Path2DControlPoint
pub opaque type PathStatus
pub opaque type PathfindingLink
pub opaque type PathfindingModifier
pub opaque type PathfindingService
pub opaque type PathfindingUseImprovedSearch
pub opaque type PausedState
pub opaque type PausedStateBreakpoint
pub opaque type PausedStateException
pub opaque type PeoplePageLayout
pub opaque type PerformanceControlService
pub opaque type PermissionLevelShown
pub opaque type PermissionsService
pub opaque type PhysicalConstraintType
pub opaque type PhysicalProperties
pub opaque type PhysicsService
pub opaque type PhysicsSettings
pub opaque type PhysicsSteppingMethod
pub opaque type PitchShiftSoundEffect
pub opaque type PlaceAssetIdsService
pub opaque type PlaceContentPreference
pub opaque type PlaceStatsService
pub opaque type PlacesService
pub opaque type Plane
pub opaque type PlaneConstraint
pub opaque type Platform
pub opaque type PlatformCloudStorageService
pub opaque type PlatformFriendsService
pub opaque type PlatformLibraries
pub opaque type PlaybackState
pub opaque type Player
pub opaque type PlayerCharacterDestroyBehavior
pub opaque type PlayerData
pub opaque type PlayerDataErrorState
pub opaque type PlayerDataLoadFailureBehavior
pub opaque type PlayerDataRecord
pub opaque type PlayerDataRecordConfig
pub opaque type PlayerDataService
pub opaque type PlayerEmulatorService
pub opaque type PlayerGui
pub opaque type PlayerHydrationService
pub opaque type PlayerListConfiguration
pub opaque type PlayerMouse
pub opaque type PlayerScripts
pub opaque type PlayerViewService
pub opaque type Players
pub opaque type Plugin
pub opaque type PluginAction
pub opaque type PluginCapabilities
pub opaque type PluginConnection
pub opaque type PluginConnectionService
pub opaque type PluginConnectionTargetType
pub opaque type PluginDebugService
pub opaque type PluginDragEvent
pub opaque type PluginGui
pub opaque type PluginGuiService
pub opaque type PluginManagementService
pub opaque type PluginManager
pub opaque type PluginManagerInterface
pub opaque type PluginMenu
pub opaque type PluginMouse
pub opaque type PluginPolicyService
pub opaque type PluginToolbar
pub opaque type PluginToolbarButton
pub opaque type PointLight
pub opaque type PointsService
pub opaque type PolicyService
pub opaque type Pose
pub opaque type PoseBase
pub opaque type PoseEasingDirection
pub opaque type PoseEasingStyle
pub opaque type PositionAlignmentMode
pub opaque type PostEffect
pub opaque type PredictionMode
pub opaque type PredictionStatus
pub opaque type PreferredInput
pub opaque type PreferredTextSize
pub opaque type PrefetchDownloadStatus
pub opaque type Preloaded
pub opaque type PrimalPhysicsSolver
pub opaque type PrismaticConstraint
pub opaque type ProceduralBehaviorSchedulerService
pub opaque type ProceduralModel
pub opaque type ProcessInstancePhysicsService
pub opaque type PromptExperienceDetailsResult
pub opaque type PropertyStatus
pub opaque type ProtectedString
pub opaque type ProximityPrompt
pub opaque type ProximityPromptExclusivity
pub opaque type ProximityPromptService
pub opaque type ProximityPromptStyle
pub opaque type PublishService
pub opaque type PyramidHandleAdornment
pub opaque type QDir
pub opaque type QFont
pub opaque type QWidgetPluginGui
pub opaque type QualityLevel
pub opaque type R15CollisionType
pub opaque type RBXScriptConnection
pub opaque type RBXScriptSignal
pub opaque type RTAnimationTracker
pub opaque type Ray
pub opaque type RayValue
pub opaque type RaycastParams
pub opaque type RaycastResult?
pub opaque type RbxAnalyticsService
pub opaque type RealtimeMedia
pub opaque type ReceiptType
pub opaque type RecommendationActionType
pub opaque type RecommendationImpressionType
pub opaque type RecommendationPages
pub opaque type RecommendationPreferenceTargetType
pub opaque type RecommendationPreferenceType
pub opaque type RecommendationService
pub opaque type Rect
pub opaque type ReflectionMetadata
pub opaque type ReflectionMetadataCallbacks
pub opaque type ReflectionMetadataClass
pub opaque type ReflectionMetadataClasses
pub opaque type ReflectionMetadataEnum
pub opaque type ReflectionMetadataEnumItem
pub opaque type ReflectionMetadataEnums
pub opaque type ReflectionMetadataEvents
pub opaque type ReflectionMetadataFunctions
pub opaque type ReflectionMetadataItem
pub opaque type ReflectionMetadataMember
pub opaque type ReflectionMetadataProperties
pub opaque type ReflectionMetadataYieldFunctions
pub opaque type ReflectionService
pub opaque type Region3
pub opaque type Region3int16
pub opaque type RejectCharacterDeletions
pub opaque type RelativeGui
pub opaque type RemoteCommandService
pub opaque type RemoteCursorService
pub opaque type RemoteDebuggerServer
pub opaque type RemoteEvent
pub opaque type RemoteFunction
pub opaque type RenderFidelity
pub opaque type RenderSettings
pub opaque type RenderingCacheOptimizationMode
pub opaque type RenderingTest
pub opaque type RenderingTestComparisonMethod
pub opaque type ReplicateInstanceDestroySetting
pub opaque type ReplicatedFirst
pub opaque type ReplicatedStorage
pub opaque type ResamplerMode
pub opaque type ReservedHighlightId
pub opaque type RestPose
pub opaque type RestPoseModel
pub opaque type ReturnKeyType
pub opaque type ReverbSoundEffect
pub opaque type ReverbType
pub opaque type RibbonNotificationService
pub opaque type RibbonTool
pub opaque type RigLabel
pub opaque type RigScale
pub opaque type RigType
pub opaque type RigidConstraint
pub opaque type RobloxPluginGuiService
pub opaque type RobloxReplicatedStorage
pub opaque type RobloxSerializableInstance
pub opaque type RobloxServerStorage
pub opaque type RocketPropulsion
pub opaque type RodConstraint
pub opaque type RollOffMode
pub opaque type RolloutState
pub opaque type RolloutValidation
pub opaque type RolloutValidationService
pub opaque type RomarkRbxAnalyticsService
pub opaque type RomarkService
pub opaque type RootImportData
pub opaque type RopeConstraint
pub opaque type Rotate
pub opaque type RotateP
pub opaque type RotateV
pub opaque type RotationCurve
pub opaque type RotationCurveKey
pub opaque type RotationOrder
pub opaque type RotationType
pub opaque type RsvpStatus
pub opaque type RtMessagingService
pub opaque type RtlTextSupport
pub opaque type RunContext
pub opaque type RunService
pub opaque type RunState
pub opaque type RunningAverageItemDouble
pub opaque type RunningAverageItemInt
pub opaque type RunningAverageTimeIntervalItem
pub opaque type RuntimeContentService
pub opaque type RuntimeScriptService
pub opaque type RuntimeUndoBehavior
pub opaque type SafeAreaCompatibility
pub opaque type SafetyService
pub opaque type SandboxedInstanceMode
pub opaque type SaveFilter
pub opaque type SavedQualitySetting
pub opaque type ScaleType
pub opaque type SceneAnalysisService
pub opaque type ScopeCheckResult
pub opaque type ScreenGui
pub opaque type ScreenInsets
pub opaque type ScreenOrientation
pub opaque type ScreenshotCapture
pub opaque type ScreenshotHud
pub opaque type Script
pub opaque type ScriptBuilder
pub opaque type ScriptChangeService
pub opaque type ScriptCloneWatcher
pub opaque type ScriptCloneWatcherHelper
pub opaque type ScriptCommitService
pub opaque type ScriptContext
pub opaque type ScriptDebugger
pub opaque type ScriptDebuggerService
pub opaque type ScriptDocument
pub opaque type ScriptEditorService
pub opaque type ScriptProfilerService
pub opaque type ScriptRegistrationService
pub opaque type ScriptRuntime
pub opaque type ScriptService
pub opaque type ScrollBarInset
pub opaque type ScrollingDirection
pub opaque type ScrollingFrame
pub opaque type Seat
pub opaque type Secret
pub opaque type SecurityCapabilities
pub opaque type Selection
pub opaque type SelectionBehavior
pub opaque type SelectionBox
pub opaque type SelectionHighlightManager
pub opaque type SelectionLasso
pub opaque type SelectionPartLasso
pub opaque type SelectionPointLasso
pub opaque type SelectionRenderMode
pub opaque type SelectionSphere
pub opaque type SelfViewConfiguration
pub opaque type SelfViewPosition
pub opaque type SensorBase
pub opaque type SensorMode
pub opaque type SensorUpdateType
pub opaque type SerializationService
pub opaque type ServerReplicator
pub opaque type ServerScriptService
pub opaque type ServerStorage
pub opaque type ServiceProvider
pub opaque type ServiceVisibility
pub opaque type ServiceVisibilityService
pub opaque type SessionCheckService
pub opaque type SessionService
pub opaque type SharedTable
pub opaque type SharedTable?
pub opaque type SharedTableRegistry
pub opaque type Shirt
pub opaque type ShirtGraphic
pub opaque type ShowAdResult
pub opaque type SignalBehavior
pub opaque type SizeConstraint
pub opaque type SkateboardController
pub opaque type SkateboardPlatform
pub opaque type Skin
pub opaque type Sky
pub opaque type SlidingBallConstraint
pub opaque type SlimAnimationDataEntity
pub opaque type SlimAnimationReplicationService
pub opaque type SlimContentProvider
pub opaque type SlimReplicationService
pub opaque type SlimService
pub opaque type Smoke
pub opaque type SmoothVoxelsUpgraderService
pub opaque type Snap
pub opaque type SnippetService
pub opaque type SocialService
pub opaque type SolidModelContentProvider
pub opaque type SolidPrimitiveType
pub opaque type SolverConvergenceMetricType
pub opaque type SolverConvergenceVisualizationMode
pub opaque type SortDirection
pub opaque type SortOrder
pub opaque type Sound
pub opaque type SoundEffect
pub opaque type SoundGroup
pub opaque type SoundService
pub opaque type SoundShimService
pub opaque type Sparkles
pub opaque type SpawnLocation
pub opaque type SpawnerService
pub opaque type SpecialKey
pub opaque type SpecialMesh
pub opaque type SphereHandleAdornment
pub opaque type SpotLight
pub opaque type SpringConstraint
pub opaque type StackFrame
pub opaque type StandalonePluginScripts
pub opaque type StandardPages
pub opaque type StartCorner
pub opaque type StartPageService
pub opaque type StarterCharacterScripts
pub opaque type StarterGear
pub opaque type StarterGui
pub opaque type StarterPack
pub opaque type StarterPlayer
pub opaque type StarterPlayerScripts
pub opaque type StartupMessageService
pub opaque type Stats
pub opaque type StatsItem
pub opaque type Status
pub opaque type StepFrequency
pub opaque type StopWatchReporter
pub opaque type StreamOutBehavior
pub opaque type StreamingIntegrityMode
pub opaque type StringValue
pub opaque type StrokeSizingMode
pub opaque type Studio
pub opaque type StudioAssetService
pub opaque type StudioAttachment
pub opaque type StudioCallout
pub opaque type StudioCameraService
pub opaque type StudioCaptureBufferStatus
pub opaque type StudioCaptureScreenshotFormat
pub opaque type StudioCaptureService
pub opaque type StudioCloseMode
pub opaque type StudioData
pub opaque type StudioDataModelType
pub opaque type StudioDeviceEmulatorService
pub opaque type StudioDeviceSimulatorService
pub opaque type StudioObjectBase
pub opaque type StudioPublishService
pub opaque type StudioScreenshotCapture
pub opaque type StudioScriptDebugEventListener
pub opaque type StudioScriptEditorColorPresets
pub opaque type StudioSdkService
pub opaque type StudioService
pub opaque type StudioStyleGuideColor
pub opaque type StudioStyleGuideModifier
pub opaque type StudioTestService
pub opaque type StudioTheme
pub opaque type StudioUserService
pub opaque type StudioWidget
pub opaque type StudioWidgetsService
pub opaque type Style
pub opaque type StyleBase
pub opaque type StyleDerive
pub opaque type StyleLink
pub opaque type StyleQuery
pub opaque type StyleRule
pub opaque type StyleSheet
pub opaque type StylingService
pub opaque type SunRaysEffect
pub opaque type SurfaceAppearance
pub opaque type SurfaceGui
pub opaque type SurfaceGuiBase
pub opaque type SurfaceGuiShape
pub opaque type SurfaceGuiSizingMode
pub opaque type SurfaceLight
pub opaque type SurfaceSelection
pub opaque type SurfaceType
pub opaque type SwimController
pub opaque type SyncScriptBuilder
pub opaque type SystemThemeService
pub opaque type SystemThemeValue
pub opaque type TableMajorAxis
pub opaque type TaskScheduler
pub opaque type Team
pub opaque type TeamCreateData
pub opaque type TeamCreatePublishService
pub opaque type TeamCreateService
pub opaque type Teams
pub opaque type Technology
pub opaque type TelemetryService
pub opaque type TeleportAsyncResult
pub opaque type TeleportOptions
pub opaque type TeleportService
pub opaque type TemporaryCageMeshProvider
pub opaque type TemporaryScriptService
pub opaque type Terrain
pub opaque type TerrainAcquisitionMethod
pub opaque type TerrainDetail
pub opaque type TerrainFace
pub opaque type TerrainIterateOperation
pub opaque type TerrainModifyOperation
pub opaque type TerrainReadOperation
pub opaque type TerrainRegion
pub opaque type TerrainWriteOperation
pub opaque type TestCase
pub opaque type TestService
pub opaque type TextBox
pub opaque type TextBoxService
pub opaque type TextButton
pub opaque type TextChannel
pub opaque type TextChatCommand
pub opaque type TextChatConfigurations
pub opaque type TextChatMessage
pub opaque type TextChatMessageProperties
pub opaque type TextChatMessageStatus
pub opaque type TextChatService
pub opaque type TextDirection
pub opaque type TextFilterContext
pub opaque type TextFilterResult
pub opaque type TextFilterTranslatedResult
pub opaque type TextGenerator
pub opaque type TextInputType
pub opaque type TextLabel
pub opaque type TextService
pub opaque type TextSource
pub opaque type TextTruncate
pub opaque type TextXAlignment
pub opaque type TextYAlignment
pub opaque type Texture
pub opaque type TextureGenerationPartGroup
pub opaque type TextureGenerationService
pub opaque type TextureGenerationUnwrappingRequest
pub opaque type TextureMode
pub opaque type TextureQueryType
pub opaque type ThirdPartyUserService
pub opaque type ThreadPoolConfig
pub opaque type ThreadState
pub opaque type ThrottlingPriority
pub opaque type ThumbnailSize
pub opaque type ThumbnailType
pub opaque type TickCountSampleMethod
pub opaque type TimerService
pub opaque type ToastNotificationService
pub opaque type TonemapperPreset
pub opaque type Tool
pub opaque type TopBottom
pub opaque type Torque
pub opaque type TorsionSpringConstraint
pub opaque type TotalCountTimeIntervalItem
pub opaque type TouchCameraMovementMode
pub opaque type TouchInputService
pub opaque type TouchMovementMode
pub opaque type TouchTransmitter
pub opaque type TraceRouteService
pub opaque type TracerService
pub opaque type TrackerExtrapolationFlagMode
pub opaque type TrackerFaceTrackingStatus
pub opaque type TrackerLodController
pub opaque type TrackerLodFlagMode
pub opaque type TrackerLodValueMode
pub opaque type TrackerMode
pub opaque type TrackerStreamAnimation
pub opaque type TrackerType
pub opaque type Trail
pub opaque type Translator
pub opaque type TremoloSoundEffect
pub opaque type TriStateBoolean
pub opaque type TriangleMeshPart
pub opaque type TrussPart
pub opaque type TutorialService
pub opaque type Tween
pub opaque type TweenBase
pub opaque type TweenInfo
pub opaque type TweenService
pub opaque type UDim
pub opaque type UDim2
pub opaque type UGCAvatarService
pub opaque type UGCValidationService
pub opaque type UIAspectRatioConstraint
pub opaque type UIBase
pub opaque type UICaptureMode
pub opaque type UIComponent
pub opaque type UIConstraint
pub opaque type UICorner
pub opaque type UIDragDetector
pub opaque type UIDragDetectorBoundingBehavior
pub opaque type UIDragDetectorDragRelativity
pub opaque type UIDragDetectorDragSpace
pub opaque type UIDragDetectorDragStyle
pub opaque type UIDragDetectorResponseStyle
pub opaque type UIDragDetectorService
pub opaque type UIDragSpeedAxisMapping
pub opaque type UIFlexAlignment
pub opaque type UIFlexItem
pub opaque type UIFlexMode
pub opaque type UIGradient
pub opaque type UIGridLayout
pub opaque type UIGridStyleLayout
pub opaque type UILayout
pub opaque type UIListLayout
pub opaque type UIPadding
pub opaque type UIPageLayout
pub opaque type UIScale
pub opaque type UIShadow
pub opaque type UISizeConstraint
pub opaque type UIStroke
pub opaque type UITableLayout
pub opaque type UITextSizeConstraint
pub opaque type UITheme
pub opaque type UiMessageType
pub opaque type UnionOperation
pub opaque type UniqueId
pub opaque type UniqueIdLookupService
pub opaque type UniversalConstraint
pub opaque type UnreliableRemoteEvent
pub opaque type UnvalidatedAssetService
pub opaque type UsageContext
pub opaque type UserCFrame
pub opaque type UserGameSettings
pub opaque type UserInputService
pub opaque type UserInputState
pub opaque type UserInputType
pub opaque type UserService
pub opaque type UserSettings
pub opaque type UserStorageService
pub opaque type VRComfortSetting
pub opaque type VRControllerModelMode
pub opaque type VRLaserPointerMode
pub opaque type VRSafetyBubbleMode
pub opaque type VRScaling
pub opaque type VRService
pub opaque type VRSessionState
pub opaque type VRStatusService
pub opaque type VRTouchpad
pub opaque type VRTouchpadMode
pub opaque type ValueBase
pub opaque type ValueCurve
pub opaque type ValueCurveKey
pub opaque type Variant?
pub opaque type Vector2
pub opaque type Vector2?
pub opaque type Vector3
pub opaque type Vector3?
pub opaque type Vector3Curve
pub opaque type Vector3Value
pub opaque type Vector3int16
pub opaque type VectorForce
pub opaque type VehicleController
pub opaque type VehicleSeat
pub opaque type VelocityConstraintMode
pub opaque type VelocityMotor
pub opaque type VersionControlService
pub opaque type VerticalAlignment
pub opaque type VerticalScrollBarPosition
pub opaque type VibrationMotor
pub opaque type VideoCapture
pub opaque type VideoCaptureService
pub opaque type VideoCaptureStartedResult
pub opaque type VideoDeviceCaptureQuality
pub opaque type VideoDeviceInput
pub opaque type VideoDisplay
pub opaque type VideoFrame
pub opaque type VideoPlayer
pub opaque type VideoSampleSize
pub opaque type VideoSampler
pub opaque type VideoScreenCaptureService
pub opaque type VideoService
pub opaque type ViewMode
pub opaque type ViewportFrame
pub opaque type VirtualCursorMode
pub opaque type VirtualInput
pub opaque type VirtualInputManager
pub opaque type VirtualUser
pub opaque type VisibilityCheckDispatcher
pub opaque type Visit
pub opaque type VisualizationMode
pub opaque type VisualizationModeCategory
pub opaque type VisualizationModeService
pub opaque type VoiceChatDistanceAttenuationType
pub opaque type VoiceChatInternal
pub opaque type VoiceChatService
pub opaque type VoiceChatState
pub opaque type VoiceClientLeaveReasons
pub opaque type VolumetricAudio
pub opaque type VoxelBuffer
pub opaque type WaterDirection
pub opaque type WaterForce
pub opaque type WebSocketClient
pub opaque type WebSocketService
pub opaque type WebSocketState
pub opaque type WebStreamClient
pub opaque type WebStreamClientState
pub opaque type WebStreamClientType
pub opaque type WebViewParams?
pub opaque type WebViewService
pub opaque type WedgePart
pub opaque type Weld
pub opaque type WeldConstraint
pub opaque type Wire
pub opaque type WireframeHandleAdornment
pub opaque type Workspace
pub opaque type WorkspaceAnnotation
pub opaque type WorldModel
pub opaque type WorldRoot
pub opaque type WrapDeformMeshProvider
pub opaque type WrapDeformer
pub opaque type WrapLayer
pub opaque type WrapLayerAutoSkin
pub opaque type WrapLayerDebugMode
pub opaque type WrapTarget
pub opaque type WrapTargetDebugMode
pub opaque type WrapTextureTransfer
pub opaque type ZIndexBehavior
pub opaque type bool?
pub opaque type buffer
pub opaque type double?
pub opaque type float?
pub opaque type int64?
pub opaque type int?